export const LOAD_INITIAL_PROPS = 'LOAD_INITIAL_PROPS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const ADD_INCOMING_MESSAGE = 'ADD_INCOMING_MESSAGE';
export const ADD_OUTGOING_MESSAGE = 'ADD_OUTGOING_MESSAGE';
